name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true

      - name: Install dependencies
        run: |
          go mod download
          go install github.com/golang/mock/mockgen@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Generate mocks
        run: make mock

      - name: Generate SQL code
        run: make sqlc

      - name: Run linter
        run: golangci-lint run

      - name: Run tests in API folder
        run: go test -v -cover ./api/...

      - name: Build
        run: go build -v ./...
